### ISSUE TITLE
udp.go:udpHandler.fetchUDPInput timeout too high

### ISSUE THREAD

**Issue by ignoramous** [Jigsaw-Code/outline-go-tun2socks#72]
At least on two occasions we've noticed _very_ _many_ `udp.go:fetchUDPInput` go routines block at [`net.UDPConn.ReadFrom`](https://github.com/Jigsaw-Code/outline-go-tun2socks/blob/7332825429/intra/udp.go#L100) for more than 60 minutes. Not unexpected since the [current timeout is set to `2h4m`](https://github.com/Jigsaw-Code/outline-go-tun2socks/blob/304acda35e1/intra/tunnel.go#L93) but unsure if such a long idle timeout is req for UDP connections, too. Isn't it the case that most routers close UDP NAT after idling for `30s`? If so, `2h4m` idle timeout might be way too high. [RFC-4787](https://tools.ietf.org/html/rfc4787) I stumbled upon, if I read it correctly, recommends at least 2mins or 5mins timeouts for UDP NAT.

One such io-wait:

```
12-27 20:46:09.819  9777     0 E Go      : goroutine 8785 [IO wait, 72 minutes]:
12-27 20:46:09.819  9777     0 E Go      : internal/poll.runtime_pollWait(0x7f7e0b7158, 0x72, 0x0)
12-27 20:46:09.819  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/runtime/netpoll.go:220 +0x3c
12-27 20:46:09.820  9777     0 E Go      : internal/poll.(*pollDesc).wait(0x4000571d18, 0x72, 0x800, 0x800, 0x0)
12-27 20:46:09.820  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:87 +0x30
12-27 20:46:09.820  9777     0 E Go      : internal/poll.(*pollDesc).waitRead(...)
12-27 20:46:09.820  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/internal/poll/fd_poll_runtime.go:92
12-27 20:46:09.820  9777     0 E Go      : internal/poll.(*FD).ReadFrom(0x4000571d00, 0x40002f0000, 0x800, 0x800, 0x0, 0x0, 0x0, 0x0, 0x0)
12-27 20:46:09.820  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/internal/poll/fd_unix.go:215 +0x154
12-27 20:46:09.820  9777     0 E Go      : net.(*netFD).readFrom(0x4000571d00, 0x40002f0000, 0x800, 0x800, 0x7f00180100, 0x7f7d91c260, 0x7f7d981b44, 0x4000189e08, 0x7f0018a000)
12-27 20:46:09.820  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/net/fd_posix.go:61 +0x3c
12-27 20:46:09.820  9777     0 E Go      : net.(*UDPConn).readFrom(0x4000310000, 0x40002f0000, 0x800, 0x800, 0x400056e920, 0x40003625a0, 0x0, 0x7f7d93a71c)
12-27 20:46:09.821  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/net/udpsock_posix.go:47 +0x3c
12-27 20:46:09.821  9777     0 E Go      : net.(*UDPConn).ReadFrom(0x4000310000, 0x40002f0000, 0x800, 0x800, 0x4000310000, 0x1, 0x0, 0x0, 0x0)
12-27 20:46:09.821  9777     0 E Go      : >/home/murtaza/.gvm/gos/go1.15/src/net/udpsock.go:118 +0x40
12-27 20:46:09.822  9777     0 E Go      : github.com/Jigsaw-Code/outline-go-tun2socks/tunnel/intra.(*udpHandler).fetchUDPInput(0x400007f6c0, 0x7f7daacfa0, 0x4000390ae0, 0x4000022440)
12-27 20:46:09.822  9777     0 E Go      : >/home/murtaza/bravehub/outline-go-tun2socks/tunnel/intra/udp.go:124 +0x2e8
12-27 20:46:09.822  9777     0 E Go      : created by github.com/Jigsaw-Code/outline-go-tun2socks/tunnel/intra.(*udpHandler).Connect
12-27 20:46:09.823  9777     0 E Go      : >/home/murtaza/bravehub/outline-go-tun2socks/tunnel/intra/udp.go:222 +0x344
```

Thoughts?

**Comment by ignoramous** [comment]
The udp timeout is now set to `5m`.
